version: '3'

services:
    php:
        container_name: symfony
        build:
            context: .
            dockerfile: docker/php/Dockerfile
            args:
                TIMEZONE: ${TIMEZONE}
        ports:
            - '8000:8000'
        volumes:
            - ./symfony/:/var/www/symfony/
        command: symfony server:start
        networks:
            - symfony
    # nginx:
    #     build:
    #         context: .
    #         dockerfile: docker/nginx/Dockerfile
    #     volumes:
    #         - ./symfony/:/var/www/symfony/
    #     ports:
    #         - 80:80
    #     networks:
    #         - symfony
    rabbitmq:
        image: 'rabbitmq:3.6-management-alpine'
        container_name: rabbitmq
        ports:
            - '5672:5672'
            - '15672:15672'
        networks:
            - symfony
networks:
    symfony:
